# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: SCIT Press
# Description of the Site
description: An innovative independent drama press
# URL of Image of the Site
#site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: 
# URL for the Image of custom Favicon
favicon-url: /assets/images/scit.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://upload.wikimedia.org/wikipedia/commons/e/ee/Bella_Rose_Arts_Centre_Stage.JPG



# Name of the Author
author-name: SCIT Press
# URL for the Image of the Author
author-image: /assets/images/scit.png
# 60 Words About the Author
author-about: SCIT Press, founded by playwright Joseph Eberle, is a pioneering publishing company focused on bold, thought-provoking plays. With a commitment to challenging conventions, SCIT Press showcases works that span genres, provoke conversation, and explore complex human experiences. Eberle's vision is to provide a platform for daring playwrights, transforming the theatrical landscape with powerful, high-impact drama.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
